#load("@rules_cc//cc:defs.bzl", "cc_binary")
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "udp_data",
    srcs = ["udp_data.cpp",],
    hdrs = ["udp_data.h",],
    deps = ["@ros//:ros_common",],
)
