load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gnss_m2_common",
    srcs = [
        "m2_gflags.cc",
    ],
    hdrs = [
        "m2_gflags.h",
    ],
    deps = [
        "//external:gflags",
    ],
)

cpplint()
